apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portal-ds-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.cp.devportal.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.cp.devportal.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.cp.devportal.appName ) | indent 6}}
  template:
    metadata:
      labels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.cp.devportal.appName ) | indent 8}}
    spec:
      containers:
        - name: dev-portal-ds
          image: {{ .Values.wso2.apk.cp.devportal.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.cp.devportal.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9443
              protocol: "TCP"
