# Default values for apk-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



wso2:
  apk:
    cp:
      devportal:
        appName: "devportal-ds"
        deployment:
          strategy: Recreate
          replicas: 1
          imagePullPolicy: IfNotPresent
          image: rakhitharr/apk-devportal:0.1.0
        ingress:
          path: /api/am/devportal
      admin:
        appName: "admin-ds"
        deployment:
          strategy: Recreate
          replicas: 1
          imagePullPolicy: IfNotPresent
          image: rakhitharr/apk-admin:0.1.0
        ingress:
          path: /api/am/admin
      publisher:
        appName: "publisher-ds"
        deployment:
          strategy: Recreate
          replicas: 1
          imagePullPolicy: IfNotPresent
          image: rakhitharr/apk-publisher:0.1.0
        ingress:
          path: /api/am/publisher
      cnpg:
        instances: 1
        clusterName: cluster-example
        appUserPassword: password
        superUserPassword: password
