apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-ds-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.cp.publisher.deployment.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" "publisher") | indent 6}}
  template:
    metadata:
      labels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" "publisher") | indent 8}}
    spec:
      containers:
        - name: publisher-ds
          image: {{ .Values.wso2.apk.cp.publisher.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.cp.publisher.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9443
              protocol: "TCP"