{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: admin-ds-service
  namespace : {{ .Release.Namespace }}
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.cp.admin.appName ) | indent 4}}
  ports:
    - name: servlet-https
      protocol: TCP
      port: 9443
{{- end -}}
