apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: {{ .Values.wso2.apk.cp.cloudNativePG.instances }}
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi