{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sts-ds-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.cp.sts.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.cp.sts.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.cp.sts.appName ) | indent 6}}
  template:
    metadata:
      labels:
        networkPolicyId: {{ .Values.wso2.apk.cp.sts.deployment.npi }}
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.cp.sts.appName ) | indent 8}}
    spec:
      containers:
        - name: sts-ds
          image: {{ .Values.wso2.apk.cp.sts.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.cp.sts.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9443
              protocol: "TCP"
            - containerPort: 8080
              protocol: "TCP"
{{ include "apl-helm.deployment.readinessProbe.http" .Values.wso2.apk.cp.sts.deployment | indent 10 }}
{{ include "apl-helm.deployment.livenessProbe.http" .Values.wso2.apk.cp.sts.deployment | indent 10 }}
{{ include "apl-helm.deployment.resources" .Values.wso2.apk.cp.sts.deployment.resources | indent 10 }}
{{- end -}}
