{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: devportal-ui-conf
data:
  Settings.js: |-
    const API_PORT=80
    const API_HOST='192.168.49.2'
    const API_TRANSPORT='http'
    const IDP_CLIENT_ID='T0Po-zLDzKtJHosmgKZZaXhABijNaFWJ'
    const IDP_DOMAIN='construct.auth0.com'

    const Settings = {
        API_PORT,
        API_HOST,
        API_TRANSPORT,
        IDP_CLIENT_ID,
        IDP_DOMAIN
    };
    if(module.exports){
        module.exports.Settings = Settings;
    }
{{- end -}}
