{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: v1
data:
  password: {{ include "apk-helm.cnpg.appUserPassword" . }}
  username: YXBw
kind: Secret
metadata:
  name: cluster-example-app-user
type: kubernetes.io/basic-auth
{{- end -}}
