{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: devportal-ds-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.cp.devportal.appName ) | indent 6}}
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            networkPolicyId: {{ .Values.wso2.apk.cp.cnpg.npi }}
      ports:
        - protocol: TCP
          port: 5432
{{- end -}}
